{% set name = "buildifier" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/buildtools/archive/{{ version }}.tar.gz
  sha256: c28eef4d30ba1a195c6837acf6c75a4034981f5b4002dda3c5aa6e48ce023cf1
  folder: src/github.com/bazelbuild/buildtools

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} >=1.12

test:
  commands:
    - buildifier --version

about:
  home: https://github.com/bazelbuild/buildtools
  license: Apache-2.0
  license_family: APACHE
  license_file: src/github.com/bazelbuild/buildtools/LICENSE
  summary: buildifier is a tool for formatting bazel BUILD and .bzl files with a standard convention.
  doc_url: https://github.com/bazelbuild/buildtools/blob/{{ version }}/buildifier/README.md
  dev_url: https://github.com/bazelbuild/buildtools

extra:
  recipe-maintainers:
    - asford
