{% set name = "buildifier" %}
{% set version = "6.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/buildtools/archive/v{{ version }}.tar.gz
  sha256: b7187e0856280feb0658ab9d629c244e638022819ded8243fb02e0c1d4db8f1c
  folder: src/github.com/bazelbuild/buildtools

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} >=1.12

test:
  commands:
    - buildifier --version

about:
  home: https://github.com/bazelbuild/buildtools
  license: Apache-2.0
  license_family: APACHE
  license_file: src/github.com/bazelbuild/buildtools/LICENSE
  summary: buildifier is a tool for formatting bazel BUILD and .bzl files with a standard convention.
  doc_url: https://github.com/bazelbuild/buildtools/blob/{{ version }}/buildifier/README.md
  dev_url: https://github.com/bazelbuild/buildtools

extra:
  recipe-maintainers:
    - asford
